global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "mercury-services"
    metrics_path: "/metrics/prometheus"
    static_configs:
      - targets:
        - "host.docker.internal:4000"
        - "host.docker.internal:4001"
        - "host.docker.internal:4002"
        - "host.docker.internal:4003"
        - "host.docker.internal:4004"
        - "host.docker.internal:4005"
        - "host.docker.internal:4006"
        - "host.docker.internal:4007"
        - "host.docker.internal:4008"
        - "host.docker.internal:4009"
        - "host.docker.internal:4010"
